import type { Metadata } from 'next'
import './globals.css'
import { dm_sans } from '@/utils/fonts';
import Navbar from '@/app/navbar';
import Footer from '@/app/footer';



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={ dm_sans.className }>

    {/* MAIN CONTAINER */ }
    <div className='flex flex-col h-screen'>

      {/* NAVBAR */ }
      <Navbar />

      {/* ROUTER */ }
      <main className='flex-grow bg-sky-950 pl-24 pr-24 pt-16 transition ease-in-out delay-150'>
        { children }
      </main>

      {/* FOOTER */ }
      <Footer />

    </div>
    </body>
    </html>
  )
}
