import type { Metadata } from 'next'
import { Akshar, Alegreya, Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/navbar';
import Footer from '@/app/footer';
import { NextFont } from 'next/dist/compiled/@next/font';

const inter: NextFont = Inter({ subsets: ['latin'] })
const akshar: NextFont = Akshar({ subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ akshar.className }>
      <div className='flex flex-col'>
        <Navbar />
        <div className='h-80 bg-sky-950'> </div>
        { children }
        <Footer />
      </div>
      </body>
    </html>
  )
}
