import type { Metadata } from 'next'
import { DM_Sans, Rubik } from 'next/font/google'
import './globals.css'
import Navbar from '@/app/navbar';
import Footer from '@/app/footer';
import { NextFont } from 'next/dist/compiled/@next/font';

const dm_sans: NextFont = DM_Sans({ subsets: ['latin']});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ dm_sans.className }>

      {/* MAIN CONTAINER */}
      <div className='flex flex-col h-screen'>
        <Navbar />
        <main className='flex-grow bg-sky-950'>
          { children }
        </main>
        <Footer />
      </div>

      </body>
    </html>
  )
}
